### ISSUE TITLE
Report on dangling terms

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/Phenex#67]
Phenex currently only warns that a file contains danglers. It would be very helpful to view a list of characters that contain the danglers.  Otherwise one has to scroll through each phenotype to find it.  

This could be displayed within the Consistency Review panel.

**Comment by wdahdul** [comment]
Also need a listing of provisional terms.

**Comment by balhoff** [comment]
Danglers and provisional terms are now checked in the Consistency Review panel.
